name: shop_app_clothes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_native_splash: ^2.4.4
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/1.jpg
    - assets/logos/2.jpg
    - assets/logos/google.jpg
    - assets/logos/fb.jpg
    - assets/logos/image.png
    - assets/logos/image1.png
    - assets/logos/image3.png
    - assets/icons/shoe.png
    - assets/icons/t-shirt.png
    - assets/icons/hat.png
    - assets/icons/coat.png
    - assets/icons/dress.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
