// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNe_Ze6p03hLS1Fl9Ofnk-mW8dvosZ1I',
    appId: '1:1089338576921:web:bb32672ec7a27e835fda88',
    messagingSenderId: '1089338576921',
    projectId: 'shop-clothes-b03f0',
    authDomain: 'shop-clothes-b03f0.firebaseapp.com',
    storageBucket: 'shop-clothes-b03f0.firebasestorage.app',
    measurementId: 'G-04DZV510VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCx5Azo8G33ugZy-9pAq18iLD-c57J6o',
    appId: '1:1089338576921:android:6ec72a786f22cc1c5fda88',
    messagingSenderId: '1089338576921',
    projectId: 'shop-clothes-b03f0',
    storageBucket: 'shop-clothes-b03f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0NREVBeKDz450xIHoZ5oHOfq5XOiGZA',
    appId: '1:1089338576921:ios:e77be5fa06367fc35fda88',
    messagingSenderId: '1089338576921',
    projectId: 'shop-clothes-b03f0',
    storageBucket: 'shop-clothes-b03f0.firebasestorage.app',
    iosBundleId: 'com.example.shopAppClothes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu0NREVBeKDz450xIHoZ5oHOfq5XOiGZA',
    appId: '1:1089338576921:ios:e77be5fa06367fc35fda88',
    messagingSenderId: '1089338576921',
    projectId: 'shop-clothes-b03f0',
    storageBucket: 'shop-clothes-b03f0.firebasestorage.app',
    iosBundleId: 'com.example.shopAppClothes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNe_Ze6p03hLS1Fl9Ofnk-mW8dvosZ1I',
    appId: '1:1089338576921:web:d982fdc6169df9165fda88',
    messagingSenderId: '1089338576921',
    projectId: 'shop-clothes-b03f0',
    authDomain: 'shop-clothes-b03f0.firebaseapp.com',
    storageBucket: 'shop-clothes-b03f0.firebasestorage.app',
    measurementId: 'G-E9QQ4LYVP6',
  );
}
